version: '3'
services:
  node_backend:
    build: .
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - "3000:8080"
    environment:
    - CHOKIDAR_USEPOLLING=true
    # - WATCHPACK_POLLING=true
    restart: always